import "@/app/globals.css"
import { Toaster } from "@/components/ui/toaster"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Toaster />
      {children}
    </>
  )
}
